Require 'yaml' explicitly as tests weren't passing because of this
Without this, running the tests with Ruby 1.9.3:

```
test_tollfree(ZATest):
NameError: uninitialized constant Phoner::Country::YAML
    /Users/rfelix/Projects/Talkdesk/forked_repos/phoner/lib/phoner/country.rb:11:in `load'
    /Users/rfelix/Projects/Talkdesk/forked_repos/phoner/lib/phoner/phone.rb:61:in `parse'
    /Users/rfelix/Projects/Talkdesk/forked_repos/phoner/test/test_helper.rb:5:in `parse_test'
    /Users/rfelix/Projects/Talkdesk/forked_repos/phoner/test/countries/za_test.rb:17:in `test_tollfree'
```